### PR TITLE
learn/events page

### PR DESCRIPTION
**Pull request by dereke**
very very rough start to a learning/events page
@AlecRust need your help to style this.
@joshski and @artemave need you to fill in some details about your talks

### CODE REVIEW

**Comment by AlecRust** [comment]
Have set up basic scaffolding for these "Learn" pages, basically matching "Work" section.

@dereke I replaced the filtered events array with an object to match the other index pages. Maybe we can add back a solution for this that works for all index pages at some point?

"Learn" has been added to main navigation. After content for the other event pages (search `TODO`) I think this is ready to merge.

**Comment by dereke** [comment]
@AlecRust I added a booking form (wired up to mailchimp) it looks a bit rubbish - and I'm not really sure about its position on the page - any ideas?

**Comment by AlecRust** [comment]
@dereke pushed some changes. Think this is ready to merge?

**Comment by dereke** [comment]
oh sweet! looks good man, just fixed a broken link but yeah I think we should do it!

**Pull request merged**
