### PR TITLE
Version of work page with content from old site - shippable

### PR DESCRIPTION
**Pull request by adiel**
Means we can ship this. Then we can extend to full case studies later.

screen shot 2016-12-06 at 17 04 05

### CODE REVIEW

**Comment by dobiedad** [comment]
👍

**Comment by AlecRust** [comment]
Imo the case study pages look good even with just the amount of text you've added for each in this PR ([similar example](https://featurist-v2.herokuapp.com/work/farmdrop/)).

I could take this content and the rest people wrote to populate the case study pages for MVP, so it's easier for people to iterate on these dedicated pages over time?

If I remove the "Code" section as-per @PaulCampbell's suggestion this can then go live?

**Comment by refractalize** [comment]
* euromoney: https://docs.google.com/document/d/1RijnFwOlvNFH07-4Ew3rGCJjnvBPnfwQmxoWip_DKns/edit
* IMD: https://docs.google.com/document/d/1DkT39dxmVw0qQI2H5WBjbu8s9SR-LEbnJK7kHenvUZE/edit

**Comment by adiel** [comment]
@AlecRust Yeah, it's just for many of these there's so little that there's nothing really to summarise on the index page. Unless we downgrade that to just logos or logs + titles/names.

**Comment by AlecRust** [comment]
Yeah that gets my vote ^

**Pull request merged**
